-- Create the proof_of_work table
CREATE TABLE public.proof_of_work (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  issue_id bigint NOT NULL,
  official_id uuid NOT NULL,
  image_url text NOT NULL,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  
  -- Primary Key
  CONSTRAINT proof_of_work_pkey PRIMARY KEY (id),
  
  -- Foreign Key to issues table (Cascade delete if the issue is deleted)
  CONSTRAINT proof_of_work_issue_id_fkey FOREIGN KEY (issue_id) REFERENCES public.issues(id) ON DELETE CASCADE,
  
  -- Foreign Key to profiles table to track which official uploaded the proof
  CONSTRAINT proof_of_work_official_id_fkey FOREIGN KEY (official_id) REFERENCES public.profiles(id)
);

-- Add an index for faster queries since you will frequently fetch proofs by issue_id
CREATE INDEX idx_proof_of_work_issue_id ON public.proof_of_work(issue_id);

-- Optional: Enable Row Level Security (RLS)
ALTER TABLE public.proof_of_work ENABLE ROW LEVEL SECURITY;

-- Optional: Create a basic policy allowing anyone to view proofs (adjust based on your privacy needs)
CREATE POLICY "Enable read access for all users" ON public.proof_of_work
    AS PERMISSIVE FOR SELECT
    TO public
    USING (true);

-- Optional: Create a policy allowing authenticated officials to insert proofs
CREATE POLICY "Enable insert for authenticated users only" ON public.proof_of_work
    AS PERMISSIVE FOR INSERT
    TO authenticated
    WITH CHECK (true);